config/routes.rb
Akccashback::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"

  root to: 'coupons#index'

  get 'ui(/:action)', controller: 'ui'
  
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :transactions, only: [:create, :new]
    resources :activities, only: [:index]
    
    member do
      get 'all_coupons'
    end
  end

  get 'register/:token', to: "users#register_confirmation", as: 'register_with_token'
  
  resources :forgot_passwords, only: [:create]
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :stores, except: [:destroy] do
    member do 
      post 'save_store'
      post 'remove_store'
    end
  end

  resources :categories, only: [:show]
  resources :ctypes, only: [:show]
  resources :kohls_categories, only: [:show]
  resources :kohls_types, only: [:show]
  resources :kohls_onlies, only: [:show]

  resources :coupons, only: [:index] do
    member do
      post 'toggle_favorite'
      post 'email_coupon'
      get 'coupon_link'
      get 'reveal_code_link'
    end

    collection do
      get 'search', to: 'coupons#search'
      get 'tab_all'
      get 'tab_coupon_codes'
      get 'tab_offers'
    end
  end

  namespace :admin do
    resources :coupons, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'get_kohls_coupons', to: 'coupons#get_kohls_coupons'
    get 'delete_kohls_coupons', to: 'coupons#delete_kohls_coupons'
    get 'get_mailer_kohls_coupons', to: 'coupons#get_mailer_kohls_coupons'
    get 'get_keywords', to: 'coupons#get_keywords'
    
    resources :activities, only: [:index]
    get 'get_activities', to: 'activities#get_activities'
  end
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  get '/pages/*id' => 'pages#show', as: :page, format: false,  path: '*id'
  
  

  

  

end

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController

  def new

  end

  def create
    user = User.where(email: params[:email]).first
    if user
      AppMailer.delay.send_forgot_password(user)
      redirect_to forgot_password_confirmation_path
    else
      flash[:danger] = params[:email].blank? ? "Email cannot be blank." : "Email is not in the system."
      redirect_to forgot_password_path
    end
  end

  def confirm

  end
end

app/views/forgot_passwords/confirm.html.haml
.page-header
  %h1 Reset Password
.row
  .s6.l6.col-md-offset-3
    .well.well-lg
      %p We have sent an email with instructions to reset your password.

app/views/forgot_passwords/new.html.haml
.page-header
  %h1 Forgot Password or User Name?
.row
  .s6.l6.col-md-offset-3
    .well.well-lg
      %p We will send you an email with a link that you can use to reset your password, it will also have your registered user name.
      = form_tag(forgot_passwords_path, 'role' => 'form') do
        .form-group
          = label_tag :email, "Email Address"
          = text_field_tag :email, params[:email], class: 'form-control'
        %fieldset.action 
          = submit_tag('Send Email', :class => 'btn btn-success')