config/routes.rb
Akccashback::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"

  root to: 'coupons#index'

  get 'ui(/:action)', controller: 'ui'
  
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :transactions, only: [:create, :new]
    resources :activities, only: [:index]
    
    member do
      get 'all_coupons'
    end
  end

  get 'register/:token', to: "users#register_confirmation", as: 'register_with_token'
  
  resources :forgot_passwords, only: [:create]
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :stores, except: [:destroy] do
    member do 
      post 'save_store'
      post 'remove_store'
    end
  end

  resources :categories, only: [:show]
  resources :ctypes, only: [:show]
  resources :kohls_categories, only: [:show]
  resources :kohls_types, only: [:show]
  resources :kohls_onlies, only: [:show]

  resources :coupons, only: [:index] do
    member do
      post 'toggle_favorite'
      post 'email_coupon'
      get 'coupon_link'
      get 'reveal_code_link'
    end

    collection do
      get 'search', to: 'coupons#search'
      get 'tab_all'
      get 'tab_coupon_codes'
      get 'tab_offers'
    end
  end

  namespace :admin do
    resources :coupons, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'get_kohls_coupons', to: 'coupons#get_kohls_coupons'
    get 'delete_kohls_coupons', to: 'coupons#delete_kohls_coupons'
    get 'get_mailer_kohls_coupons', to: 'coupons#get_mailer_kohls_coupons'
    get 'get_keywords', to: 'coupons#get_keywords'
    
    resources :activities, only: [:index]
    get 'get_activities', to: 'activities#get_activities'
  end
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  get '/pages/*id' => 'pages#show', as: :page, format: false,  path: '*id'
  
  

  

  

end

app/models/store.rb
class Store < ActiveRecord::Base

  validates :name, presence: true
  validates :id_of_store, presence: true, uniqueness: true
  has_many :coupons, -> { order "end_date ASC" }
  has_and_belongs_to_many :users

  #belongs_to :activity
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.with_coupons
    Store.joins(:coupons).where(["end_date >= :time ", { :time => DateTime.current }]).uniq
  end

  def self.load_stores
    oo = Roo::Excel.new("#{Rails.root}/lsstores.xls")
    oo.default_sheet = oo.sheets.first
    2.upto(2) do | line |
      store_hash = {
        name: oo.cell(line, 'A'),
        id_of_store: oo.cell(line, 'C').to_i,
        description: oo.cell(line, 'D'),
        home_page_url: oo.cell(line, 'G'),
        commission: oo.cell(line, 'AA').split("%").first.to_f
      }

      if oo.cell(line, 'H') == 'Active'
        store_hash[:active_commission] = true
      else
        store_hash[:active_commission] = false
      end
      
      ['jpg','gif','png'].each do | ext |
        store_hash[:store_img] = 'http://merchant.linksynergy.com/fs/logo/lg_' + store_hash[:id_of_store].to_s + '.' + ext  
        break if Faraday.head(store_hash[:store_img]).status == 200
      end
      new_store = Store.new(store_hash)
      new_store.save
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  include CouponCodesOffers
  before_filter :require_user, only:[:save_store, :remove_store]

  def index
    @stores = Store.friendly.to_a
    @stores_featured = Store.with_coupons.limit(12)

    @store_array = []
    @stores.each do | store |
      @store_array << store.name
    end
  end

  def show
    @store = Store.friendly.find(params[:id])
    @coupons = Coupon.where(["store_id = :store AND end_date >= :time ", { :store => @store.id, :time => DateTime.current }]).order( 'end_date ASC' )

    @codes_count = coupon_codes(@coupons)
    @offers_count = coupon_offers(@coupons)
  end

  def save_store
    @store = Store.find_by_id(params[:store_id])
    current_user.stores << @store
    flash[:success] = "#{@store.name} has been added to your favorites."
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def remove_store
    @store = Store.find_by_id(params[:store_id])
    current_user.stores.delete(@store)
    flash[:success] = "#{@store.name} has been removed from your favorites."
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper

  def number_of_coupons(store)
    Coupon.where(["store_id = :store AND end_date >= :time ", { :store => store.id, :time => DateTime.current }]).count
  end

end

app/views/stores/index.html.haml
.container
  .page-header
    %h3 STORES
  .row
    .panel.panel-default
      .panel-heading
        %h3.panel-title Today's Featured Stores
      .panel-body
        .row
          -@stores_featured.each_with_index do | featured_store, i |
            -if i %  6 == 0 
              .row
            .l2.s2
              = link_to image_tag(featured_store.store_img, size: "125x40", alt: featured_store.name), { action: 'show', id: featured_store }, class: "thumbnail"
    .panel.panel-default
      .panel-heading
        %h3.panel-title Stores by Name
      .panel-body
        - g = @store_array.group_by{ |c| c.upcase[0..0] }
        .panel-group#accordion
          - ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'].each do |letter|
            .panel.panel-default
              .panel-heading
                %h4.panel-title
                  %a.accordion-toggle{"data-toggle" => 'collapse', 'data-parent' => '#accordion', 'href' => "#collapse_#{letter}" }
                    = "#{letter}"
              %div#collapse.panel-collapse.collapse{:id => letter }
                .panel-body
                  - store_g = g[letter] || []
                  - store_g.each do | store |
                    .l3.s3
                      =link_to "#{store}", { action: 'show', id: Store.find_by_name(store) }
                      %span.badge=number_of_coupons(Store.find_by_name(store))

app/views/stores/remove_store.js.erb
$("#remove_store_<%= @store.id %>").hide("slow");

app/views/stores/save_store.js.erb
$("#save_store_<%= @store.id %>").hide("slow");

app/views/stores/show.html.haml
-provide(:title, "Welcome to ZUUZLO Coupons | #{@store.name}")
.container
  .page-header
    %h1 #{@store.name}
    -if logged_in? && current_user.store_ids.include?(@store.id) == FALSE
      = link_to save_store_store_path(@store, store_id: @store.id), method: 'post', remote: true, id: "save_store_#{@store.id}", class: "btn btn-default btn-xs" do
        %span.glyphicon.glyphicon-ok
        Add to Favorite Stores
  .row
    .l12.s12
      .panel.panel-default
        .panel-heading
          .panel-title 
            Latest coupons for
            %i
              #{@store.name}
          = render 'shared/coupon_tabs'
        = render 'shared/coupon_tab_content'  