config/routes.rb
Akccashback::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"

  root to: 'coupons#index'

  get 'ui(/:action)', controller: 'ui'
  
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :transactions, only: [:create, :new]
    resources :activities, only: [:index]
    
    member do
      get 'all_coupons'
    end
  end

  get 'register/:token', to: "users#register_confirmation", as: 'register_with_token'
  
  resources :forgot_passwords, only: [:create]
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :stores, except: [:destroy] do
    member do 
      post 'save_store'
      post 'remove_store'
    end
  end

  resources :categories, only: [:show]
  resources :ctypes, only: [:show]
  resources :kohls_categories, only: [:show]
  resources :kohls_types, only: [:show]
  resources :kohls_onlies, only: [:show]

  resources :coupons, only: [:index] do
    member do
      post 'toggle_favorite'
      post 'email_coupon'
      get 'coupon_link'
      get 'reveal_code_link'
    end

    collection do
      get 'search', to: 'coupons#search'
      get 'tab_all'
      get 'tab_coupon_codes'
      get 'tab_offers'
    end
  end

  namespace :admin do
    resources :coupons, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'get_kohls_coupons', to: 'coupons#get_kohls_coupons'
    get 'delete_kohls_coupons', to: 'coupons#delete_kohls_coupons'
    get 'get_mailer_kohls_coupons', to: 'coupons#get_mailer_kohls_coupons'
    get 'get_keywords', to: 'coupons#get_keywords'
    
    resources :activities, only: [:index]
    get 'get_activities', to: 'activities#get_activities'
  end
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  get '/pages/*id' => 'pages#show', as: :page, format: false,  path: '*id'
  
  

  

  

end

app/views/shared/_admin_activity.html.haml
- activities.each do | activity |
  %tr
    %td
      = activity.user_name
    %td
      = activity.store_name
    %td
      = activity.clicks
    %td
      = number_to_currency( activity.sales_cents.to_f / 100 )
    %td
      = number_to_currency( activity.commission_cents.to_f / 100 )

app/views/shared/_admin_coupon.html.haml
- coupons.each do | coupon |
  - row_class = coupon.end_date > Time.now ? '' : 'danger'
  %tr{ :class => row_class }
    %td
      = image_tag("#{coupon.image}", size: "40x40")
    %td
      = coupon.code
    %td
      = coupon.title
    %td
      = coupon.description
    %td
      = coupon.end_date
    %td
      = link_to "Edit", edit_admin_coupon_path(coupon)
      = link_to "Delete", admin_coupon_path(coupon), :method => :delete

app/views/shared/_ads_display.html.haml
%h4.carousel
  Register to remove ads!
%script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
/ cashback
%ins.adsbygoogle{"data-ad-client" => "ca-pub-1902425673775970", "data-ad-format" => "auto", "data-ad-slot" => "1117298183", :style => "display:block"}
:javascript
  (adsbygoogle = window.adsbygoogle || []).push({});

app/views/shared/_coupon_modal.html.haml
.modal.fade{ "id" => "coupon_modal_#{coupon.id}","tabindex"=>"-1", "role" => "dialog", "aria-labelledby" => "mySmallModalLabel", "aria-hidden" => "true" }
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        Send this coupon to inbox.
        %button.close{"type"=>"button", "data-dismiss"=>"modal"}
          %span{"aria-hidden" => "true"}
            %span.glyphicon.glyphicon-remove-circle
          %span.sr-only
            Close
      .modal-body
        %div{:id => "flash_hook_#{coupon.id}"}
        = form_tag(email_coupon_coupon_path(coupon, coupon_id: coupon.id), method: 'post', remote: true) do
          .form-group
            = label_tag :email, "Email Address"
            = email_field_tag :email, params[:email], class: 'form-control'
          = hidden_field_tag :user_id, current_user.id
          %fieldset.action 
            = submit_tag('Send Email', :class => 'btn btn-success')
      .modal-footer
        %small.text-left
          Your email will only be used to send this coupon. This is not a subscription service and the reciever will not receive spam.

app/views/shared/_coupon_reveal_modal.html.haml
.modal.fade{ "id" => "coupon_reveal_modal_#{coupon.id}","tabindex"=>"-1", "role" => "dialog", "aria-labelledby" => "couponRevealModal", "aria-hidden" => "true" }
  .modal-dialog.modal-sm
    .modal-content.text-center
      .modal-header
        %h4.modal-title{"id" => "couponRevealModal"}
          Copy the Coupon Code
          %button.close{"type"=>"button", "data-dismiss"=>"modal"}
            %span{"aria-hidden" => "true"}
              %span.glyphicon.glyphicon-remove-circle
            %span.sr-only
              Close
      .modal-body
        %p
          Past the code during checkout.
        %h4
          #{coupon.code}
        = button_link(coupon)
      .modal-footer
        %p.text-center
          Show coupon codes on home page by registering.
        

app/views/shared/_coupon_tab_content.html.haml
#coupons.transitions-enabled.centered.infinite-scroll.clearfix.masonry
  = render @coupons
    

app/views/shared/_coupon_tabs.html.haml
%ul.nav.nav-pills.nav-stacked
  %li.active
    = link_to tab_all_coupons_path, method: 'get', remote: true, id: 'tab_all_pill', :rel => "nofollow" do
      %span.badge.pull-right
        #{@coupons.count}
      %span.glyphicon.glyphicon-tags
      ALL
  %li
    = link_to tab_coupon_codes_coupons_path, method: 'get', remote: true, id: 'tab_coupon_codes_pill', :rel => "nofollow" do
      %span.badge.pull-right
        #{@codes_count}
      %span.glyphicon.glyphicon-filter
      COUPON CODES
  %li
    = link_to tab_offers_coupons_path, method: 'get', remote: true, id: 'tab_offers_pill', :rel => "nofollow" do
      %span.badge.pull-right
        #{@offers_count}
      %span.glyphicon.glyphicon-filter
      OFFERS

app/views/shared/_coupons.html.haml
- coupons.each_with_index do |coupon, i|
  - cache_unless logged_in?, coupon do
    .l4.s4{ 'id' => "coupon_#{coupon.id}", 'data-type' => "#{coupon_type(coupon)}" }
      .thumbnail.coupon
        = product_image(coupon)
        .caption
          %h4 #{coupon.title.split("- ").last}
          -if logged_in?
            = favorites(controller_name, coupon)
            = email_coupon(coupon)
            = render partial: 'shared/coupon_modal', locals: { coupon: coupon }
          .well.well-sm
            %p
              %b #{coupon.description}
            -if coupon.code 
              %h5
                Coupon Code:
                %b
                  #{coupon.code}
            %span.label.label-default
              #{coupon.store_commission} 
              \% cash back
          = button_link(coupon)
          %h5
            - if coupon.preview?
              = not_released(coupon)
            - else
              = time_left_display(coupon)
          -if coupon.kohls_categories.size > 0
            %h5
              = render coupon.kohls_categories

app/views/shared/_footer.html.haml
.footer
  %p.pull-right
    =link_to "Back to Top", "#"
  %p 
    = link_to "Anti-spam Policy", page_path('anti-spam_policy'), rel: 'nofollow'
    |
    = link_to "DMCA Notice", page_path('dmca_notice'), rel: 'nofollow'
    |
    = link_to "E-mail Policy", page_path('e-mail_policy'), rel: 'nofollow'
    |
    = link_to "Privacy Policy", page_path('privacy_policy'), rel: 'nofollow'
    |
    = link_to "Terms of Use", page_path('terms_of_use'), rel: 'nofollow'
    |
    = link_to "Terms of Service", page_path('terms_of_service'), rel: 'nofollow'
  %p
    %small
      © 2015 -2012 Copyright AllKohlsCoupons.com - All Rights Reserved.

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top.yamm{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{type: 'button', "data-toggle" => 'collapse', "data-target" => ".navbar-ex1-collapse"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to root_url, class: 'navbar-brand' do
      %span.glyphicon.glyphicon-tags
      All Kohls Coupons Cash Back
  .collapse.navbar-collapse.navbar-ex1-collapse 
    %ul.nav.navbar-nav
      - if logged_in?
        %li{:class => "#{'active' if user_home? }" }
          =link_to user_url(current_user) do
            %span.glyphicon.glyphicon-home
            Home
      - else
        %li{:class => "#{'active' if current_page?(root_url)}"}
          =link_to root_url do
            %span.glyphicon.glyphicon-home
            Home
      %li.dropdown{:class => "#{'active' if filt_page? }" }
        %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
          %span.glyphicon.glyphicon-filter
          Coupon Categories
          %b.caret
        %ul.dropdown-menu
          %li
            .yamm-content
              .row
                %ul.col-sm-4.list-unstyled
                  %li
                    %p
                      %strong
                        %u
                          Category
                  - KohlsCategory.with_coupons.each do |cat|
                    %li
                      - cache(cat) do
                        = link_to kohls_category_path(cat) do
                          #{cat.name}
                %ul.col-sm-4.list-unstyled
                  %li
                    %p
                      %strong
                        %u
                          Type 
                  - KohlsType.with_coupons.each do |typ|
                    %li
                      - cache(typ) do
                        = link_to kohls_type_path(typ) do
                          #{typ.name}
                %ul.col-sm-4.list-unstyled
                  %li
                    %p
                      %strong
                        %u
                          Only at Kohls
                  -KohlsOnly.with_coupons.each do |only|
                    %li
                      - cache(only) do
                        = link_to kohls_only_path(only) do
                          #{only.name}
    %form.navbar-form.navbar-left{ action: search_coupons_path, method: "get"}
      %div.form-group
        %input.form-control{type:"text", name: "search_term", placeholder:"Search Term", value: "" }
      = button_tag(type: "submit", class: "btn btn-primary" ) do
        %span.glyphicon.glyphicon-search
        Search
    - if logged_in?  
      %ul.nav.navbar-nav.navbar-right 
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            %span.glyphicon.glyphicon-user
            #{current_user.user_name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              = link_to 'Invite a Friend', '#'
            %li
              = link_to 'Sign Out', sign_out_path
            - if current_user.admin?
              %li.divider
              %li
                = link_to 'View Coupons', admin_coupons_path
              %li
                = link_to 'Create New Coupon', new_admin_coupon_path
              %li
                = link_to 'Activities', admin_activities_path
              %li
                = link_to 'Create New Email', admin_get_mailer_kohls_coupons_path
              %li
                =link_to "Get Keywords", admin_get_keywords_path
    - else
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to sign_in_path do
            %span.glyphicon.glyphicon-log-in
            Sign in
        %li
          =link_to new_user_path do
            %span.glyphicon.glyphicon-tasks
            Register

app/views/shared/_message_modal.html.haml
#flash_hook  
  .modal.fade{ "id" => "message_modal","tabindex"=>"-1", "role" => "dialog", "aria-labelledby" => "mySmallModalLabel", "aria-hidden" => "true" }
    .modal-dialog
      .modal-content
        %h4
          #{msg}
          %button.close{"type"=>"button", "data-dismiss"=>"modal"}
            %span{"aria-hidden" => "true"}
              %span.glyphicon.glyphicon-remove-circle
            %span.sr-only
              Close

app/views/shared/_messages.html.haml
-#flash.each do |name, msg|
  -#%div(class="alert alert-#{name}"){:id => "flash"}
    -#%a.close(data-dismiss='alert') &#215;
    -#= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
-flash.each do |name, msg|    
  -if msg.is_a?(String)
    #message_modal.modal.fade{"aria-hidden" => "false", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content{:class => "modal-alert-#{name}"}
          .modal-body
            = "#{msg}"
            %button.close{"data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"}
                %span.glyphicon.glyphicon-remove-circle
              %span.sr-only
                Close

app/views/shared/display_coupons.js.erb
$('#coupons').append('<%= j (render partial: "coupons/coupon", collection: @coupons, as: :coupon) %>'); 
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@coupons) %>');
var offerItems = $('#coupons').find("div[data-type='offers']").length;
var codeItems = $('#coupons').find("div[data-type='coupon_codes']").length;
$('.offer_count').text(offerItems);
$('.code_count').text(codeItems);
$("#coupons").isotope({ filter: "*" });

if($("li:has(a#tab_coupon_codes_pill)").hasClass("active")){
  $("#coupons").isotope({ filter: ".coupon_codes" });
};

if($("li:has(a#tab_offers_pill)").hasClass("active")){
  $("#coupons").isotope({ filter: ".offers" });
};

app/views/shared/old_coupons.html.haml
- coupons.each_with_index do |coupon, i|
  - cache_unless logged_in?, coupon do
    .l4.s4{ 'id' => "coupon_#{coupon.id}", 'data-type' => "#{coupon_type(coupon)}" }
      .thumbnail.coupon
        = product_image(coupon)
        .caption
          %h4 #{coupon.title.split("- ").last}
          -if logged_in?
            = favorites(controller_name, coupon)
            = email_coupon(coupon)
            = render partial: 'shared/coupon_modal', locals: { coupon: coupon }
          .well.well-sm
            %p
              %b #{coupon.description}
            -if coupon.code 
              %h5
                Coupon Code:
                %b
                  #{coupon.code}
            %span.label.label-default
              #{coupon.store_commission} 
              \% cash back
          = button_link(coupon)
          %h5
            - if coupon.preview?
              = not_released(coupon)
            - else
              = time_left_display(coupon)
          -if coupon.kohls_categories.size > 0
            %h5
              = render coupon.kohls_categories