config/routes.rb
Akccashback::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"

  root to: 'coupons#index'

  get 'ui(/:action)', controller: 'ui'
  
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :transactions, only: [:create, :new]
    resources :activities, only: [:index]
    
    member do
      get 'all_coupons'
    end
  end

  get 'register/:token', to: "users#register_confirmation", as: 'register_with_token'
  
  resources :forgot_passwords, only: [:create]
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :stores, except: [:destroy] do
    member do 
      post 'save_store'
      post 'remove_store'
    end
  end

  resources :categories, only: [:show]
  resources :ctypes, only: [:show]
  resources :kohls_categories, only: [:show]
  resources :kohls_types, only: [:show]
  resources :kohls_onlies, only: [:show]

  resources :coupons, only: [:index] do
    member do
      post 'toggle_favorite'
      post 'email_coupon'
      get 'coupon_link'
      get 'reveal_code_link'
    end

    collection do
      get 'search', to: 'coupons#search'
      get 'tab_all'
      get 'tab_coupon_codes'
      get 'tab_offers'
    end
  end

  namespace :admin do
    resources :coupons, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'get_kohls_coupons', to: 'coupons#get_kohls_coupons'
    get 'delete_kohls_coupons', to: 'coupons#delete_kohls_coupons'
    get 'get_mailer_kohls_coupons', to: 'coupons#get_mailer_kohls_coupons'
    get 'get_keywords', to: 'coupons#get_keywords'
    
    resources :activities, only: [:index]
    get 'get_activities', to: 'activities#get_activities'
  end
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  get '/pages/*id' => 'pages#show', as: :page, format: false,  path: '*id'
  
  

  

  

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  require 'action_view'
  include ActionView::Helpers::DateHelper

  NULL_ATTRS = %w( code restriction )

  
  before_save :nil_if_blank

  belongs_to :store

  has_many :coupon_kohls_categories, dependent: :destroy
  has_many :kohls_categories, :through => :coupon_kohls_categories
  
  has_many :coupon_kohls_onlies, dependent: :destroy
  has_many :kohls_onlies, :through => :coupon_kohls_onlies
  
  has_many :coupon_kohls_types, dependent: :destroy
  has_many :kohls_types, :through => :coupon_kohls_types

  #has_and_belongs_to_many :kohls_categories, after_add: :touch_updated_at, after_remove: :touch_updated_at
  #has_and_belongs_to_many :kohls_onlies, after_add: :touch_updated_at, after_remove: :touch_updated_at
  #has_and_belongs_to_many :kohls_types, after_add: :touch_updated_at, after_remove: :touch_updated_at
  has_and_belongs_to_many :users
  
  validates :id_of_coupon, presence: true, uniqueness: true
  validates :title, presence: true
  validates :link, presence: true

  mount_uploader :image, CouponImageUploader

  def touch_updated_at(object)
    self.touch if persisted?
  end

  def time_left
    distance_of_time_in_words(end_date, DateTime.now)
  end

  def time_difference
    end_date - DateTime.now
  end

  def store_name
    Store.find(self.store_id).name
  end

  def store_image
    Store.find(self.store_id).store_img
  end

  def store_commission
    Store.find(self.store_id).commission / 2
  end

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("lower(description) LIKE ?", "%#{search_term.downcase}%")
  end

  def preview?
    if start_date > DateTime.now
      true
    else
      false
    end
  end

  def time_til_good
    distance_of_time_in_words(start_date, DateTime.now)
  end

  def self.active_coupons
    where(["end_date >= :time", { :time => DateTime.current }]).order( 'end_date ASC' )
  end

  protected

  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < AdminController

  include AdminLoadSeo
  
  def new
    @coupon = Coupon.new
  end

  def create
    @coupon = Coupon.create(coupon_params)
    if @coupon.save
      flash[:success] = "You have added a new coupon."
      redirect_to new_admin_coupon_path
    else
      flash[:danger] = "Please correct the below errors."
      render 'new'
    end
  end

  def edit
    @coupon = Coupon.find(params[:id])
    render 'new'
  end

  def update
    @coupon = Coupon.find(params[:id])

    if params[:term] == ""
      
      if @coupon.update(coupon_params)
        flash[:success] = "Coupon updated."
        redirect_to admin_coupons_path
      else
        render 'index'
      end
    else
      @new_image = KohlsTransactions.find_product_image(params[:term])
      flash[:success] = "See image below, cut and past url to update coupon image."
      render 'new'
    end
  end

  def destroy
    coupon = Coupon.find(params[:id])
    removed_coupon = RemovedCoupon.new(id_of_coupon: coupon.id_of_coupon)
    
    if removed_coupon.save
      coupon.destroy
      flash[:success] = "You have removed a coupon."
      redirect_to admin_coupons_path
    else
      flash[:danger] = "Something is wrong coupon was not removed. Try again."
      render 'index'
    end
  end

  def index
    @coupon_count = Coupon.count
    @coupons = Coupon.order('end_date ASC').load
  end

  def get_kohls_coupons
    count_start = Coupon.count 
    KohlsTransactions.kohls_update_coupons
    count_finish = Coupon.count
    
    if count_finish > count_start
      flash[:success] = "Kohls Coupons are updated, you imported #{count_finish - count_start} coupons."
    else
      flash[:danger] = "No new coupons were imported"
    end

    redirect_to admin_coupons_path
  end

  def delete_kohls_coupons
    delete_coupons = []
    Coupon.all.each do | coupon |
      delete_coupons << coupon.id if coupon.end_date < Time.now
    end
    Coupon.destroy(delete_coupons)
    flash[:success] = "Deleted #{delete_coupons.count} coupons."
    redirect_to admin_coupons_path
  end

  def clean_tables
    coupons = Coupon.all.each do | coupon|
      
    end

  end

  def get_mailer_kohls_coupons
    @codes_coupons = Coupon.where(["end_date >= :time AND start_date <= :time AND code IS NOT NULL", { :time => DateTime.current }]).order( 'end_date ASC' ).limit(5)
    @offers_coupons = Coupon.where(["end_date >= :time AND start_date <= :time AND code IS NULL", { :time => DateTime.current }]).order( 'end_date ASC' ).limit(5)
  end

  def get_keywords
    
    type = params[:type]

    if type
      klass = Object.const_get type
      
      case type
      when "KohlsCategory"
        type_id = params['type_k_cat']['type_id']
      when "KohlsType"
        type_id = params['type_k_type']['type_id']
      when "KohlsOnly"
        type_id = params['type_k_only']['type_id']
      else
        flash[:danger] = "Please select type and chose a category!"
        render 'get_keywords'
      end

      type_name = klass.find(type_id)
      coupons = type_name.coupons
      @description = seo_description(coupons, type_name)
      @keywords = seo_keywords(coupons, type_name)
    end
  end

  private

  def coupon_params
    params.require(:coupon).permit(:id, :id_of_coupon, :title, :description, :start_date, :end_date, :code, :restriction, :link, :impression_pixel, :image, :store_id, :coupon_source_id, :remote_image_url )
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  include LoadCoupons
  include CouponCodesOffers
  include LoadSeo

  before_filter :require_user, only:[:toggle_favorite, :email_coupon]

  def index
    @coupons = Coupon.active_coupons.paginate(:page => params[:page]).order( 'end_date ASC' )
    load_coupon_offer_code(@coupons)
    load_cal_picts(@coupons)
    render :index, locals: { title: "Home", meta_keywords: seo_keywords(@coupons, nil), meta_description: seo_description(@coupons, nil ) } 
  end

  def search
    @coupons = Coupon.search_by_title(params[:search_term])
    @term = params[:search_term]
    load_coupon_offer_code(@coupons)
    load_cal_picts(@coupons)
  end

  def toggle_favorite
    @coupon = Coupon.find_by_id(params[:coupon_id])
    @refer_controller =  Rails.application.routes.recognize_path(request.referrer)[:controller]
    @action_name = Rails.application.routes.recognize_path(request.referrer)[:action]
  
    if current_user.coupon_ids.include?(@coupon.id)
      current_user.coupons.delete(@coupon)
      flash[:success] = "Coupon has been removed from your favorites."
    else
      current_user.coupons << @coupon
      flash[:success] = "Coupon has been added to your favorites."
    end
    
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def tab_all
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def tab_coupon_codes
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def tab_offers
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def email_coupon
    @coupon = Coupon.find_by_id(params[:coupon_id])
    @user = User.find_by_id(params[:user_id])
    @email = params[:email]
    if @email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
      AppMailer.delay.email_coupon(@email, @user, @coupon)
      flash[:success] = "You have send the coupon to #{params[:email]}"
    else
      flash[:danger] = "#{params[:email]} is not a valid email!"
    end
    
    respond_to do |format|
      format.html do  
        redirect_to :back
      end
      format.js
    end
  end

  def coupon_link
    if Coupon.exists?(params[:id])
      coupon = Coupon.find_by_id(params[:id])
    else
      coupon = Coupon.last
    end
    
    if logged_in?
      if coupon.coupon_source_id == 1
        link = coupon.link + "&u1=" + current_user.cashback_id
      else
        link = coupon.link + "?sid=" + current_user.cashback_id
      end
    else
      if coupon.coupon_source_id == 1
        link = coupon.link + "&u1=akccb"
      else
        link = coupon.link + "?sid=akccb"
      end
    end

    redirect_to link
  end

  def reveal_code_link
    if Coupon.exists?(params[:id])
      @coupon = Coupon.find_by_id(params[:id])
    else
      @coupon = Coupon.last
    end
 
    respond_to do |format|
      format.html do
      end
      format.js
    end
  end
end

app/helpers/coupons_helper.rb
module CouponsHelper

  def button_link(coupon)
    link_to coupon_link_coupon_url(coupon), class: "btn btn-primary link_button", rel: "nofollow", target: "_blank" do
      capture_haml do
        haml_concat "Shop Now"
        haml_tag 'span.glyphicon.glyphicon-chevron-right'
      end
    end
  end

  def time_left_display(coupon)
    if coupon.time_difference < 1.day
      capture_haml do
        haml_tag 'span.label.label-danger' do
          haml_tag 'span.glyphicon.glyphicon-time'
          haml_concat "Expires in #{coupon.time_left}"
        end
      end
    elsif coupon.time_difference < 3.day

      capture_haml do
        haml_tag 'span.label.label-warning' do
          haml_tag 'span.glyphicon.glyphicon-time'
          haml_concat "Expires in #{coupon.time_left}"
        end
      end
    else
      capture_haml do
        haml_tag 'span.label.label-success' do
          haml_tag 'span.glyphicon.glyphicon-time'
          haml_concat "Expires in #{coupon.time_left}"
        end
      end
    end  
  end

  def coupon_type(coupon)
    if coupon.code
      'coupon_codes'
    else
      'offers'
    end
  end

  def favorites(controller, coupon)
    if current_user.coupon_ids.include?(coupon.id)
      link_to toggle_favorite_coupon_path(coupon, coupon_id: coupon.id), method: 'post', remote: true, id: "toggle_favorite_#{coupon.id}", class: "btn btn-default btn-xs fav_toggle", "data-toggle" => "tooltip", "data-placement" => "left", "title" => "remove from favorites" do
        capture_haml do
          haml_tag 'span.glyphicon.glyphicon-heart'
        end
      end
    else
      link_to toggle_favorite_coupon_path(coupon, coupon_id: coupon.id), method: 'post', remote: true, id: "toggle_favorite_#{coupon.id}", class: "btn btn-default btn-xs fav_toggle", "container" => 'body', "data-toggle" => "tooltip", "data-placement" => "left", "title" => "add to favorites" do
        capture_haml do
          haml_tag 'span.glyphicon.glyphicon-heart-empty'
        end
      end
    end
  end

  def product_image(coupon)
    
    if coupon.image
      image_tag("#{coupon.image}", size: "125x125", class: "img-circle", alt: "#{coupon.title}")
    else
      image_tag( "#{coupon.store_image}",size: "125x125", alt: "#{coupon.title}" )
    end
  end

  def email_coupon(coupon)
    button_tag(nil, class: "btn btn-default btn-xs email_tool_tip", id: "coupon_email_button_#{coupon.id}", "data-toggle" => "modal", "data-target" => "#coupon_modal_#{coupon.id}", "container" => 'body', "rel" => "tooltip", "data-placement" => "right", "title" => "email coupon") do
      capture_haml do
        haml_tag "span.glyphicon.glyphicon-envelope"
      end
    end
  end

  def not_released(coupon)
    capture_haml do
      haml_tag 'span.label.label-info' do
        haml_tag 'span.glyphicon.glyphicon-time'
        haml_concat "Valid in #{coupon.time_til_good}"
      end
    end
  end

  def cache_key_for_coupon(coupon)
    count          = Coupon.count
    max_updated_at = Coupon.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "coupons/#{coupon.id}-#{count}-#{max_updated_at}"
  end

  def show_ad?
    prng = Random.new

    if prng.rand(100) < 5
      true
    else
      false
    end
  end

  def category_links(coupon)
    render coupon.kohls_categories + coupon.kohls_types + coupon.kohls_onlies
  end

  def reveal_code_button(coupon)
    link_to reveal_code_link_coupon_url(coupon), method: 'get', remote: true, class: "btn btn-default btn-xs", id: "coupon_reveal_button_#{coupon.id}", rel: "nofollow" do
      #, onclick: "window.open('#','_blank');"
      capture_haml do
        haml_concat "Reveal Code"
      end
    end

=begin    
    link_to reveal_code_link_coupon_url(coupon), class: "btn btn-default btn-xs", id: "coupon_reveal_button_#{coupon.id}", rel: "nofollow", target: "_blank", "data-toggle" => "modal", "data-target" => "#coupon_reveal_modal_#{coupon.id}" do
      capture_haml do
        haml_concat "Reveal Code"
      end
    end
#=end
=begin
    button_tag(nil, class: "btn btn-default btn-xs", id: "coupon_reveal_button_#{coupon.id}", "data-toggle" => "modal", "data-target" => "#coupon_reveal_modal_#{coupon.id}", "container" => 'body') do
      capture_haml do
        haml_concat "Reveal Code"
      end
    end
=end
  end
end

app/views/admin/coupons/get_keywords.html.haml
.page-header
  %h1 Admin - Description and Keywords
.row
  = bootstrap_form_tag url: '/admin/get_keywords', method: 'get' , :html => {:id => 'toggleForm'} do |f|
    .s12.l12
      = f.form_group :type, label: { text: "Select Type you would like to search for."}, help: "Must select a Type!" do
        .row
          .s2.l2
            = f.radio_button :type, 'KohlsCategory', label: "KohlsCategory", 'data-toggle' => "#type_k_cat_type_id" 
          .s2.l2  
            = select("type_k_cat", "type_id", KohlsCategory.with_coupons.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {class: "form-control two three", style: "display: none" })
        .row
          .l2.s2
            = f.radio_button :type, 'KohlsType', label: "KohlsType", 'data-toggle' => "#type_k_type_type_id" 
          .l2.s2
            = select("type_k_type", "type_id", KohlsType.with_coupons.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {class: "form-control three one", style: "display: none" })
        .row
          .l2.s2
            = f.radio_button :type, 'KohlsOnly' , label: "KohlsOnly", 'data-toggle' => "#type_k_only_type_id"
          .l2.s2
            = select("type_k_only", "type_id", KohlsOnly.with_coupons.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {class: "form-control", style: "display: none" })

      %p
        = f.submit "Show Coupons", class: "btn btn-success"
  - if @description
    %p
      = "#{@description}"
    %p
      = "#{@keywords}"

app/views/admin/coupons/get_mailer_kohls_coupons.html.haml
.page-header
  %h1 Admin - Email - Coupons
.row
  %p
    All Kohls Coupons is please to offer the following latest great deals at Kohls.  Please visit Kohls.com using the Get Deal button.  Also, don't forget to visit the new AllKohlsCoupons Cash Back site
    = link_to "CashBack.AllKohlsCoupons.com", page_url('landing')
    You can also visit
    = link_to "AllKohlsCoupons.com", "http://allkohlscoupons.com"
  %h3 Newest Coupon Codes to use at Kohls
  %p Copy the coupon code and click the Get Deal button.
  = render partial: 'admin/shared/email_coupons', locals: { coupons: @codes_coupons }
  %h3 Newest Offer to use at Kohls
  = render partial: 'admin/shared/email_coupons', locals: { coupons: @offers_coupons }
  %p If you choose to register at CashBack.AllKohlsCoupons.com, please use the links from the site prior to shopping at Kohl's so you get cash back credit.

app/views/admin/coupons/index.html.haml
.page-header
  %h1 Admin - All Coupons
.row
  .s3.l3
    = button_to "Add New Coupons", { action: "get_kohls_coupons" }, method: :get, class: "btn btn-success"
  .s3.l3
    = button_to "Delete Old Coupons", { action: "delete_kohls_coupons" }, method: :get, class: "btn btn-danger"
%h1
  = @coupon_count
  Total Coupons
%table.table
  %tr
    %th Image
    %th Code
    %th Title
    %th Description
    %th End Date
    %th Action
  = render partial: 'shared/admin_coupon', locals: { coupons: @coupons }

app/views/admin/coupons/new.html.haml
.page-header
  %h1 Admin - Add Coupon
.row
  .s6.l6.col-md-offset-3
    .well.well-lg
      = bootstrap_form_for [:admin, @coupon] do |f|
        = f.alert_message "Please fix the errors below."
        = f.text_field :id_of_coupon
        = f.text_field :title
        = f.text_field :description
        = f.text_field :code
        = f.text_field :restriction
        = f.text_field :link
        = f.text_field :impression_pixel
        = image_tag("#{@coupon.image}", size: "40x40")
        = text_field_tag(:term)
        - if @new_image
          = image_tag("#{@new_image}", size: "40x40") 
          = @new_image
        = f.url_field :remote_image_url
        = f.hidden_field :image_cache
        = f.number_field :store_id
        = f.number_field :coupon_source_id
        = f.date_field :start_date, label: 'Start Date', class: 'form-control'
        = f.date_field :end_date, label: 'End Date', class: 'form-control'
        %p.text-center
          = f.submit class: "btn btn-lg btn-success"